apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-pvc
  namespace: todo-phase-v
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Using DigitalOcean Block Storage class
  storageClassName: do-block-storage